### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by BillSam** [Silverpeas/Silverpeas-Core#1359]
Hello team

I have a security concern that I would like to raise with you, I just created an account at https://tracker.silverpeas.org/ but not yet approved. Let me know how I can raise it. 
Thanks

**Comment by mmoqui** [comment]
Hi Sam. I'm sorry but I don't know who you are. I didn't get any relevant any information about you in the Internet. You use different identifiers or references, some of which are fakes.

**Comment by BillSam** [comment]
Hello Miguel,
Which information would help

**Comment by BillSam** [comment]
I have updated the profile,

**Comment by mmoqui** [comment]
I activated your account in your issue tracker
